version: 3

jobs:
  build:
    docker:
      - image: python:3.11

    working_directory: /app

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: pip install -r requirements.txt

      - run:
          name: Run tests
          command: pytest

      - store_artifacts:
          path: test-reports

      - store_test_results:
          path: test-reports

workflows:
  version: 3
  build_and_test:
    jobs:
      - build
